
resilience4j:
  circuitbreaker:
    instances:
      productOfferingConsumerCommandKey:
        slidingWindowType: TIME_BASED
        failureRateThreshold: 50
        slidingWindowSize: 150
        minimumNumberOfCalls: 2
        slowCallDurationThreshold: 50000
        slowCallRateThreshold: 100
        waitDurationInOpenState: 120000ms
        permittedNumberOfCallsInHalfOpenState: 2
  bulkhead:
    instances:
        productOfferingConsumerCommandKey:
          maxWaitDuration: 10ms
          maxConcurrentCalls: 4  
