server:
  port: 8087

productOffering:
  consumer:
    bootstrap:
      server:
        address: localhost:9093
    groupId: productImport_id
    topic: resting
  publisher:
    topic: ProductImportResponse
kafka:
  acknowledgment:
    sleep:
      time: 30000
swiProductImport:
  webService:
    soap-action: document/http://siebel.com/asi/V0:SWIProductImportUpsert
    url: http://localhost:8081/SWIProductImportUpsert
