
resilience4j:
  circuitbreaker:
    instances:
      productOfferingConsumerCommandKey:
        slidingWindowType: COUNT_BASED
        failureRateThreshold: 50
        slidingWindowSize: 10
        minimumNumberOfCalls: 4
        slowCallDurationThreshold: 30000
        slowCallRateThreshold: 100
        waitDurationInOpenState: 120000ms
        permittedNumberOfCallsInHalfOpenState: 3
  bulkhead:
    instances:
        productOfferingConsumerCommandKey:
          maxConcurrentCalls: 1  

  retry:
    instances:
      productOfferingConsumerCommandKey:
        maxRetryAttempts: 2
        waitDuration: 1000
        retryExceptions:
        -   java.net.ConnectException

