server:
  port: 8087

productOffering:
  consumer:
    bootstrap:
      server:
        address: localhost:9092
    groupId: productImport_id
    topic: rest
  publisher:
    topic: ProductImportResponse

kafka:
  nack:
    sleep:
      time: 30000
    
retry:
  max-attempts: 3
  backoff-delay: 1000
  backoff-multiplier: 1

client:
  soap-action: document/http://siebel.com/asi/V0:SWIProductImportUpsert
  default-uri: http://localhost:8081/SWIProductImportUpsert
  timeout: 40000
